// Code generated by "stringer -type=Opcode"; DO NOT EDIT

package main

import "fmt"

const _Opcode_name = "AddMovePrintScanBNZClearMultSearch"

var _Opcode_index = [...]uint8{0, 3, 7, 12, 16, 19, 24, 28, 34}

func (i Opcode) String() string {
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return fmt.Sprintf("Opcode(%d)", i)
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
