// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package golyb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Add-0]
	_ = x[Move-1]
	_ = x[Print-2]
	_ = x[Scan-3]
	_ = x[Loop-4]
	_ = x[Clear-5]
	_ = x[Mult-6]
	_ = x[Search-7]
}

const _Opcode_name = "AddMovePrintScanLoopClearMultSearch"

var _Opcode_index = [...]uint8{0, 3, 7, 12, 16, 20, 25, 29, 35}

func (i Opcode) String() string {
	if i < 0 || i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
